import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarClock, CheckCircle2, Copy, ExternalLink, Loader2, MessageCircle, Phone, Search, Trash2, UserCheck, Users, Video } from 'lucide-react';
import { Modal } from '@/components/ui/Modal';
import { DangerConfirmModal } from '@/components/ui/DangerConfirmModal';
import { Spinner } from '@/components/ui/Spinner';
import { useToast } from '@/components/ui/Toast';
import { useAuth } from '@/hooks/useAuth';
import { assignWebinarLeadCloser, assignWebinarLeadsCloser, deleteWebinarLead, fetchStaffMembers, fetchWebinarLeads, logWebinarCallWithOrder, queryKeys } from '@/lib/queries';
import type { WebinarLead, WebinarLeadStatus } from '@/lib/types';
import { cn, formatDateTime } from '@/lib/utils';

const CLOSER_OPTIONS: { value: WebinarLeadStatus; label: string }[] = [
  { value: 'to_call', label: 'À appeler' }, { value: 'nrp', label: 'NRP — ne répond pas' },
  { value: 'callback', label: 'À rappeler' }, { value: 'not_interested', label: 'Pas intéressé / annulé' },
  { value: 'in_delivery', label: 'Confirmé / en livraison' },
];
const FILTER_OPTIONS: { value: WebinarLeadStatus; label: string }[] = [...CLOSER_OPTIONS, { value: 'delivered', label: 'Livré' }, { value: 'returned', label: 'Retour / refusé' }];
const STATUS_LABEL: Record<WebinarLeadStatus, string> = { new: 'À appeler', to_call: 'À appeler', nrp: 'NRP — ne répond pas', callback: 'À rappeler', not_interested: 'Pas intéressé / annulé', confirmed: 'Confirmé / en livraison', in_delivery: 'Confirmé / en livraison', delivered: 'Livré', returned: 'Retour / refusé' };

export function AdminWebinarLeads() {
  const toast = useToast(); const qc = useQueryClient(); const { profile } = useAuth();
  const leadsQ = useQuery({ queryKey: queryKeys.adminWebinarLeads, queryFn: fetchWebinarLeads });
  const staffQ = useQuery({ queryKey: queryKeys.adminStaff, queryFn: fetchStaffMembers, enabled: !!profile?.is_admin });
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<WebinarLeadStatus | 'all'>('all');
  const [selected, setSelected] = useState<WebinarLead | null>(null); const [deleting, setDeleting] = useState<WebinarLead | null>(null);
  const [confirmingPurchase, setConfirmingPurchase] = useState(false); const [callStatus, setCallStatus] = useState<WebinarLeadStatus>('nrp');
  const [closer, setCloser] = useState(''); const [note, setNote] = useState(''); const [followUp, setFollowUp] = useState(''); const [saving, setSaving] = useState(false);
  const [assigning, setAssigning] = useState<WebinarLead | null>(null); const [assignedCloser, setAssignedCloser] = useState('');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set()); const [bulkCloser, setBulkCloser] = useState(''); const [sortBy, setSortBy] = useState<'date' | 'closer' | 'crm' | 'ecom' | 'live'>('date');
  const [bulkDeleting, setBulkDeleting] = useState(false); const [confirmDeleteMode, setConfirmDeleteMode] = useState<null | 'selected' | 'all'>(null);
  const leads = leadsQ.data ?? [];
  const filtered = useMemo(() => { const needle = search.trim().toLowerCase(); const rows = leads.filter((lead) => (status === 'all' || lead.status === status) && (!needle || [lead.full_name, lead.phone_raw, lead.email, lead.wilaya_name, lead.commune].some((value) => value.toLowerCase().includes(needle)))); return [...rows].sort((a, b) => { if (sortBy === 'live') return Number(b.attended_live) - Number(a.attended_live); if (sortBy === 'closer') return (a.closer_name ?? 'zzzz').localeCompare(b.closer_name ?? 'zzzz'); if (sortBy === 'crm') return a.status.localeCompare(b.status); if (sortBy === 'ecom') return (a.delivery_orders?.[0]?.ecom_situation ?? 'zzzz').localeCompare(b.delivery_orders?.[0]?.ecom_situation ?? 'zzzz'); return b.created_at.localeCompare(a.created_at); }); }, [leads, search, status, sortBy]);
  const stats = useMemo(() => ({ total: leads.length, toCall: leads.filter((lead) => ['new', 'to_call', 'nrp', 'callback'].includes(lead.status)).length, confirmed: leads.filter((lead) => ['confirmed', 'in_delivery', 'delivered'].includes(lead.status)).length }), [leads]);
  // The registered, still-active closers — the single source for attribution, so
  // a call can only be credited to a real team member (no more free-text typos).
  const activeClosers = useMemo(() => (staffQ.data ?? []).filter((member) => member.is_active).map((member) => `${member.first_name} ${member.last_name}`.trim()).filter(Boolean), [staffQ.data]);

  function openCall(lead: WebinarLead) {
    setSelected(lead); const current = ['new', 'confirmed', 'delivered', 'returned'].includes(lead.status) ? 'to_call' : lead.status; setCallStatus(current as WebinarLeadStatus);
    const profileName = profile ? `${profile.first_name ?? ''} ${profile.last_name ?? ''}`.trim() : '';
    // Admin picks the closer from the list (default: whoever is already assigned).
    // A closer logging their own call is credited to themselves, locked.
    setCloser(profile?.is_admin ? (lead.closer_name || '') : profileName);
    setNote(lead.latest_call_note || ''); setFollowUp(lead.next_follow_up_at ? toLocalInput(lead.next_follow_up_at) : '');
  }
  async function saveCall() {
    if (!selected || !closer.trim()) { toast.error('Indique le nom du closer.'); return; }
    if (callStatus === 'callback' && !followUp) { toast.error('Choisis la date du prochain rappel.'); return; }
    if (callStatus === 'in_delivery' && !selected.delivery_orders?.length) { setConfirmingPurchase(true); return; }
    setSaving(true); try { const result = await logWebinarCallWithOrder({ leadId: selected.id, status: callStatus, closerName: closer.trim(), note: note.trim() || null, nextFollowUpAt: callStatus === 'callback' && followUp ? new Date(followUp).toISOString() : null }); toast.success(result.created ? 'Appel enregistré et commande ajoutée.' : 'Appel enregistré. La commande existait déjà.'); setSelected(null); await Promise.all([qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }), qc.invalidateQueries({ queryKey: queryKeys.adminDeliveryOrders }), qc.invalidateQueries({ queryKey: queryKeys.adminSalesAnalytics })]); } catch (error) { toast.error(error instanceof Error ? error.message : 'Enregistrement impossible.'); } finally { setSaving(false); }
  }
  async function approvePurchase() {
    if (!selected) return; setSaving(true);
    try { const result = await logWebinarCallWithOrder({ leadId: selected.id, status: 'in_delivery', closerName: closer.trim(), note: note.trim() || null, nextFollowUpAt: null }); toast.success(result.created ? 'Vente confirmée : commande ajoutée dans Commandes.' : 'La commande existait déjà. Aucun doublon créé.'); setConfirmingPurchase(false); setSelected(null); await Promise.all([qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }), qc.invalidateQueries({ queryKey: queryKeys.adminDeliveryOrders }), qc.invalidateQueries({ queryKey: queryKeys.adminSalesAnalytics })]); } catch (error) { toast.error(error instanceof Error ? error.message : 'Confirmation impossible.'); } finally { setSaving(false); }
  }
  async function approveDelete() {
    if (!deleting) return; setSaving(true);
    try { await deleteWebinarLead(deleting.id); toast.success('Prospect et commande liée supprimés.'); setDeleting(null); await Promise.all([qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }), qc.invalidateQueries({ queryKey: queryKeys.adminDeliveryOrders }), qc.invalidateQueries({ queryKey: queryKeys.adminSalesAnalytics })]); } catch (error) { toast.error(error instanceof Error ? error.message : 'Suppression impossible.', 'Suppression centralisée impossible'); } finally { setSaving(false); }
  }
  async function approveAssignment() { if (!assigning || !assignedCloser) return; setSaving(true); try { await assignWebinarLeadCloser(assigning.id, assignedCloser); toast.success(`${assigning.full_name} attribué à ${assignedCloser}.`); setAssigning(null); setAssignedCloser(''); await qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }); } catch (error) { toast.error(error instanceof Error ? error.message : 'Attribution impossible.'); } finally { setSaving(false); } }
  async function approveBulkAssignment() { if (selectedIds.size === 0 || !bulkCloser) return; setSaving(true); try { await assignWebinarLeadsCloser([...selectedIds], bulkCloser); toast.success(`${selectedIds.size} prospect(s) attribué(s) à ${bulkCloser}.`); setSelectedIds(new Set()); setBulkCloser(''); await qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }); } catch (error) { toast.error(error instanceof Error ? error.message : 'Attribution impossible.'); } finally { setSaving(false); } }
  // Bulk delete goes lead-by-lead (each also removes its linked E-com colis via
  // the edge function), collecting successes/failures like the Commandes page.
  async function runBulkDelete(ids: string[]) {
    if (!ids.length) return;
    setBulkDeleting(true); let success = 0; let failed = 0;
    for (const id of ids) { try { await deleteWebinarLead(id); success += 1; } catch { failed += 1; } }
    setBulkDeleting(false); setConfirmDeleteMode(null); setSelectedIds(new Set());
    toast.success(`${success} prospect(s) supprimé(s)${failed ? ` · ${failed} non supprimé(s)` : ''}.`);
    await Promise.all([qc.invalidateQueries({ queryKey: queryKeys.adminWebinarLeads }), qc.invalidateQueries({ queryKey: queryKeys.adminDeliveryOrders }), qc.invalidateQueries({ queryKey: queryKeys.adminSalesAnalytics })]);
  }
  async function copyPublicLink() { const url = `${window.location.origin}/inscription-webinar`; try { await navigator.clipboard.writeText(url); toast.success('Lien du formulaire copié.'); } catch { toast.error(`Copie ce lien : ${url}`); } }

  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-aurel-orange"><Video className="h-5 w-5" /><span className="text-sm font-semibold uppercase tracking-wide">Webinar CRM</span></div><h1 className="text-3xl font-bold text-aurel-ink">Prospects & appels</h1><p className="mt-1 text-slate-600">Tous les formulaires apparaissent ici, avec ou sans visionnage du webinar.</p></div><div className="flex flex-wrap gap-2"><button type="button" className="btn-primary" onClick={copyPublicLink}>Copier le lien <Copy className="h-4 w-4" /></button><a className="btn-outline" href="/inscription-webinar" target="_blank" rel="noreferrer">Voir le formulaire <ExternalLink className="h-4 w-4" /></a></div></header>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Kpi icon={Users} label="Prospects qualifiés" value={stats.total} color="orange" /><Kpi icon={Phone} label="À appeler / rappeler" value={stats.toCall} color="orange" /><Kpi icon={UserCheck} label="Commandes confirmées" value={stats.confirmed} color="green" /></div>
    <section className="card overflow-hidden">
      <div className="flex flex-wrap gap-3 border-b border-zinc-200 p-4">
        <label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-zinc-400" /><input className="input pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nom, WhatsApp, email, wilaya…" /></label>
        <select className="input w-52" value={status} onChange={(e) => setStatus(e.target.value as WebinarLeadStatus | 'all')}><option value="all">Tous les statuts</option>{FILTER_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>
        <select className="input w-52" value={sortBy} onChange={(e) => setSortBy(e.target.value as typeof sortBy)}><option value="date">Trier par : date</option><option value="closer">Trier par : closer</option><option value="crm">Trier par : statut CRM</option><option value="ecom">Trier par : statut E-com</option><option value="live">Trier par : vue du live</option></select>
        {profile?.is_admin && <><select className="input w-52" value={bulkCloser} onChange={(e) => setBulkCloser(e.target.value)}><option value="">Attribuer à…</option>{(staffQ.data ?? []).filter((member) => member.is_active).map((member) => { const name = `${member.first_name} ${member.last_name}`.trim(); return <option key={member.id} value={name}>{name}</option>; })}</select><button type="button" className="btn-primary" disabled={saving || selectedIds.size === 0 || !bulkCloser} onClick={approveBulkAssignment}><UserCheck className="h-4 w-4" /> Attribuer ({selectedIds.size})</button><button type="button" className="btn-outline text-red-600" disabled={saving || bulkDeleting || selectedIds.size === 0} onClick={() => setConfirmDeleteMode('selected')}><Trash2 className="h-4 w-4" /> Supprimer les choisis ({selectedIds.size})</button><button type="button" className="btn-outline text-red-600" disabled={saving || bulkDeleting || filtered.length === 0} onClick={() => setConfirmDeleteMode('all')}><Trash2 className="h-4 w-4" /> Tout supprimer ({filtered.length})</button></>}
      </div>
      {leadsQ.isLoading ? <Spinner label="Chargement des prospects…" /> : leadsQ.isError ? <div className="p-8 text-center text-red-600">Impossible de charger les prospects.</div> : filtered.length === 0 ? <div className="p-10 text-center text-zinc-500">Aucun prospect pour ces filtres.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1240px] text-sm"><thead className="bg-zinc-50 text-left text-[11px] font-semibold uppercase tracking-wide text-zinc-500"><tr><th className="px-3 py-3"><input type="checkbox" aria-label="Sélectionner tous les prospects affichés" checked={filtered.length > 0 && filtered.every((lead) => selectedIds.has(lead.id))} onChange={(e) => setSelectedIds(e.target.checked ? new Set(filtered.map((lead) => lead.id)) : new Set())} /></th><th className="px-4 py-3">Prospect</th><th className="px-4 py-3">Webinar</th><th className="px-4 py-3">Livraison</th><th className="px-4 py-3">Closer</th><th className="px-4 py-3">Statut CRM</th><th className="px-4 py-3">Statut E-com Delivery</th><th className="px-4 py-3">Dernier suivi</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-zinc-100">{filtered.map((lead) => <LeadRow key={lead.id} lead={lead} selected={selectedIds.has(lead.id)} onToggle={() => setSelectedIds((current) => { const next = new Set(current); if (next.has(lead.id)) next.delete(lead.id); else next.add(lead.id); return next; })} onCall={() => openCall(lead)} onDelete={() => setDeleting(lead)} onAssign={profile?.is_admin ? () => { setAssigning(lead); setAssignedCloser(lead.closer_name ?? ''); } : undefined} />)}</tbody></table></div>}
    </section>
    <Modal open={!!selected} onClose={() => !saving && setSelected(null)} title="Suivi du prospect" maxWidth="max-w-2xl">{selected && <div className="space-y-5"><div className="rounded-card-sm bg-zinc-50 p-4"><div className="font-bold text-zinc-950">{selected.full_name}</div><div className="mt-1 text-sm text-zinc-600">{selected.phone_raw} · {selected.email}</div><div className="mt-1 text-xs text-zinc-500"><MapPinText lead={selected} /></div></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Closer *">{profile?.is_admin ? <select className="input" value={closer} onChange={(e) => setCloser(e.target.value)}><option value="">Choisir un closer</option>{activeClosers.map((name) => <option key={name} value={name}>{name}</option>)}{closer && !activeClosers.includes(closer) && <option value={closer}>{closer} (hors liste)</option>}</select> : <input className="input" value={closer} readOnly title="Attribué automatiquement à toi" />}</Field><Field label="Résultat de l'appel *"><select className="input" value={callStatus} onChange={(e) => setCallStatus(e.target.value as WebinarLeadStatus)}>{CLOSER_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field>{callStatus === 'callback' && <Field label="Prochain rappel *"><input className="input" type="datetime-local" value={followUp} onChange={(e) => setFollowUp(e.target.value)} /></Field>}</div><Field label="Notes de l'appel"><textarea className="input min-h-28 resize-y" maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} /></Field><div className="flex flex-wrap justify-between gap-2"><a className="btn-outline" href={whatsappUrl(selected.phone_normalized)} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4" /> WhatsApp</a><div className="flex gap-2"><button type="button" className="btn-outline" disabled={saving} onClick={() => setSelected(null)}>Annuler</button><button type="button" className="btn-primary" disabled={saving} onClick={saveCall}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />} Enregistrer</button></div></div></div>}</Modal>
    <Modal open={confirmingPurchase} onClose={() => !saving && setConfirmingPurchase(false)} title="Confirmer la commande" maxWidth="max-w-md"><p className="text-zinc-700">Cette commande est-elle confirmée ?</p><p className="mt-2 text-sm text-zinc-500">Oui ajoutera immédiatement le prospect dans Commandes. Non ne changera rien.</p><div className="mt-6 flex justify-end gap-2"><button className="btn-outline" disabled={saving} onClick={() => setConfirmingPurchase(false)}>Non</button><button className="btn-primary" disabled={saving} onClick={approvePurchase}>{saving && <Loader2 className="h-4 w-4 animate-spin" />} Oui, confirmer</button></div></Modal>
    <Modal open={!!deleting} onClose={() => !saving && setDeleting(null)} title="Supprimer ce prospect ?" maxWidth="max-w-md"><p className="text-zinc-700">Cette action supprimera définitivement <strong>{deleting?.full_name}</strong>.</p><p className="mt-2 text-sm text-zinc-500">Si une commande est liée, son colis sera d’abord supprimé chez E-com, puis la commande et le prospect seront retirés d’Aurel. Si E-com refuse, aucune donnée Aurel ne sera supprimée.</p><div className="mt-6 flex justify-end gap-2"><button className="btn-outline" disabled={saving} onClick={() => setDeleting(null)}>Non</button><button className="btn-primary bg-red-600 hover:bg-red-700" disabled={saving} onClick={approveDelete}>{saving && <Loader2 className="h-4 w-4 animate-spin" />} Oui, tout supprimer</button></div></Modal>
    <Modal open={!!assigning} onClose={() => !saving && setAssigning(null)} title="Attribuer le prospect" maxWidth="max-w-md"><p className="mb-4 text-sm text-zinc-600">Choisis le closer responsable de <strong>{assigning?.full_name}</strong>.</p><select className="input" value={assignedCloser} onChange={(e) => setAssignedCloser(e.target.value)}><option value="">Choisir un closer</option>{(staffQ.data ?? []).filter((member) => member.is_active).map((member) => { const name = `${member.first_name} ${member.last_name}`.trim(); return <option key={member.id} value={name}>{name}</option>; })}</select><div className="mt-6 flex justify-end gap-2"><button className="btn-outline" disabled={saving} onClick={() => setAssigning(null)}>Annuler</button><button className="btn-primary" disabled={saving || !assignedCloser} onClick={approveAssignment}>Confirmer l’attribution</button></div></Modal>
    <Modal open={confirmDeleteMode === 'selected'} onClose={() => !bulkDeleting && setConfirmDeleteMode(null)} title="Supprimer les prospects choisis ?" maxWidth="max-w-md"><p className="text-zinc-700">Supprimer définitivement <strong>{selectedIds.size}</strong> prospect(s) sélectionné(s) ?</p><p className="mt-2 text-sm text-zinc-500">Les commandes liées et leurs colis E-com seront aussi supprimés. Si E-com refuse un colis, ce prospect-là restera intact.</p><div className="mt-6 flex justify-end gap-2"><button className="btn-outline" disabled={bulkDeleting} onClick={() => setConfirmDeleteMode(null)}>Non</button><button className="btn-primary bg-red-600 hover:bg-red-700" disabled={bulkDeleting} onClick={() => runBulkDelete([...selectedIds])}>{bulkDeleting && <Loader2 className="h-4 w-4 animate-spin" />} Oui, supprimer</button></div></Modal>
    <DangerConfirmModal open={confirmDeleteMode === 'all'} onClose={() => setConfirmDeleteMode(null)} onConfirm={() => runBulkDelete(filtered.map((lead) => lead.id))} busy={bulkDeleting} count={filtered.length} title="Tout supprimer (liste filtrée) ?" description={<span>Supprime <strong>tous les {filtered.length} prospects actuellement affichés</strong> (selon la recherche / le filtre en cours), ainsi que leurs commandes et colis E-com liés.</span>} confirmLabel="Tout supprimer" />
  </div>;
}

function LeadRow({ lead, selected, onToggle, onCall, onDelete, onAssign }: { lead: WebinarLead; selected: boolean; onToggle: () => void; onCall: () => void; onDelete: () => void; onAssign?: () => void }) { const order = lead.delivery_orders?.[0]; return <tr className="align-top hover:bg-zinc-50/70"><td className="px-3 py-3"><input type="checkbox" aria-label={`Sélectionner ${lead.full_name}`} checked={selected} onChange={onToggle} /></td><td className="px-4 py-3"><div className="font-semibold text-zinc-900">{lead.full_name}</div><a className="text-xs text-aurel-teal hover:underline" href={whatsappUrl(lead.phone_normalized)} target="_blank" rel="noreferrer">{lead.phone_raw}</a><div className="text-[11px] text-zinc-400">{lead.email}</div></td><td className="px-4 py-3"><span className={cn('badge', lead.attended_live ? 'badge-green' : 'badge-slate')}>{lead.attended_live ? 'Oui' : 'Non'}</span></td><td className="px-4 py-3"><MapPinText lead={lead} /></td><td className="px-4 py-3">{lead.closer_name ?? '—'}<div className="text-[10px] text-zinc-400">{lead.call_count} appel(s)</div></td><td className="px-4 py-3"><LeadStatus status={lead.status} /></td><td className="px-4 py-3">{order ? <><span className="badge badge-teal">{order.ecom_situation || (order.ecom_tracking ? 'En préparation' : 'Pas encore envoyée')}</span>{order.ecom_tracking && <div className="mt-1 font-mono text-[10px] text-zinc-500">{order.ecom_tracking}</div>}</> : <span className="text-xs text-zinc-400">Aucune commande</span>}</td><td className="px-4 py-3 text-xs text-zinc-500">{lead.last_call_at ? formatDateTime(lead.last_call_at) : `Inscrit ${formatDateTime(lead.created_at)}`}{lead.next_follow_up_at && <div className="mt-1 text-aurel-orange"><CalendarClock className="mr-1 inline h-3 w-3" />{formatDateTime(lead.next_follow_up_at)}</div>}<div className="mt-1 max-w-56 line-clamp-2 text-zinc-400">{lead.latest_call_note}</div></td><td className="px-4 py-3"><div className="flex flex-wrap justify-end gap-1.5">{onAssign && <button type="button" className="btn-outline px-2.5 py-1.5 text-xs" onClick={onAssign}><UserCheck className="h-3.5 w-3.5" /> Attribuer</button>}<button type="button" className="btn-outline px-2.5 py-1.5 text-xs" onClick={onCall}><Phone className="h-3.5 w-3.5" /> Suivi</button><button type="button" aria-label="Supprimer le prospect" className="btn-outline px-2.5 py-1.5 text-red-600" onClick={onDelete}><Trash2 className="h-3.5 w-3.5" /></button></div></td></tr>; }
function MapPinText({ lead }: { lead: WebinarLead }) { return <><span className="font-medium text-zinc-700">{lead.wilaya_name}</span> · {lead.commune}<div className="max-w-56 truncate text-[11px] text-zinc-400" title={lead.address}>{lead.address}</div></>; }
function LeadStatus({ status }: { status: WebinarLeadStatus }) { const color = status === 'delivered' ? 'badge-green' : ['confirmed', 'in_delivery'].includes(status) ? 'badge-teal' : ['not_interested', 'returned'].includes(status) ? 'badge-red' : 'badge-orange'; return <span className={cn('badge', color)}>{STATUS_LABEL[status]}</span>; }
function Kpi({ icon: Icon, label, value, color }: { icon: typeof Users; label: string; value: number; color: 'orange' | 'green' }) { return <div className="kpi"><div className="kpi-label"><Icon className={cn('h-4 w-4', color === 'green' ? 'text-green-600' : 'text-aurel-orange')} />{label}</div><div className="kpi-value">{value}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}</label>; }
function whatsappUrl(phone: string) { return `https://wa.me/${phone.startsWith('0') ? `213${phone.slice(1)}` : phone}`; }
function toLocalInput(value: string) { const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
