import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Save, Trash2 } from 'lucide-react';
import { fetchWebinarFormSettings, queryKeys, saveWebinarFormSettings } from '@/lib/queries';
import { useToast } from '@/components/ui/Toast';
import type { WebinarFormExtraField, WebinarFormSettings } from '@/lib/types';

export function AdminFormBuilder() {
  const toast = useToast(); const qc = useQueryClient();
  const settingsQ = useQuery({ queryKey: queryKeys.webinarFormSettings, queryFn: () => fetchWebinarFormSettings(false) });
  const [form, setForm] = useState<WebinarFormSettings | null>(null);
  useEffect(() => { if (settingsQ.data) setForm(settingsQ.data); }, [settingsQ.data]);
  if (!form) return <div className="p-8">Chargement…</div>;
  const addSection = () => setForm({ ...form, sections: [...form.sections, { id: crypto.randomUUID(), title: 'Nouvelle section', description: '' }] });
  const addField = () => setForm({ ...form, extra_fields: [...form.extra_fields, { id: crypto.randomUUID(), label: 'Nouvelle question', type: 'text', required: false }] });
  async function save() { const current = form; if (!current || !window.confirm('Publier ces modifications sur le formulaire public ?')) return; try { await saveWebinarFormSettings({ eyebrow: current.eyebrow, title: current.title, description: current.description, image_url: current.image_url, sections: current.sections, extra_fields: current.extra_fields, google_sheet_url: current.google_sheet_url, backup_webhook_url: current.backup_webhook_url }); await qc.invalidateQueries({ queryKey: queryKeys.webinarFormSettings }); toast.success('Formulaire publié.'); } catch (e) { toast.error(e instanceof Error ? e.message : 'Erreur.'); } }
  const updateField = (id: string, patch: Partial<WebinarFormExtraField>) => setForm({ ...form, extra_fields: form.extra_fields.map((f) => f.id === id ? { ...f, ...patch } : f) });
  return <div className="space-y-6"><header><h1 className="text-3xl font-bold text-aurel-ink">Formulaire</h1><p className="mt-1 text-slate-600">Modifie le nom, l’image, les sections et ajoute des questions sans toucher au code.</p></header>
    <section className="card-padded grid gap-4"><label><span className="label">Petit titre</span><input className="input" value={form.eyebrow} onChange={(e) => setForm({ ...form, eyebrow: e.target.value })} /></label><label><span className="label">Nom du formulaire</span><input className="input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span className="label">Description</span><textarea className="input min-h-20" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label><span className="label">URL de l’image (facultatif)</span><input className="input" value={form.image_url ?? ''} onChange={(e) => setForm({ ...form, image_url: e.target.value || null })} /></label></section>
    <section className="card-padded"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Sections d’information</h2><button className="btn-outline" onClick={addSection}><Plus className="h-4 w-4" /> Section</button></div><div className="space-y-3">{form.sections.map((section) => <div key={section.id} className="grid gap-2 rounded-card-sm border p-3 md:grid-cols-[1fr_2fr_auto]"><input className="input" value={section.title} onChange={(e) => setForm({ ...form, sections: form.sections.map((s) => s.id === section.id ? { ...s, title: e.target.value } : s) })} /><input className="input" value={section.description} onChange={(e) => setForm({ ...form, sections: form.sections.map((s) => s.id === section.id ? { ...s, description: e.target.value } : s) })} /><button className="btn-danger" onClick={() => setForm({ ...form, sections: form.sections.filter((s) => s.id !== section.id) })}><Trash2 className="h-4 w-4" /></button></div>)}</div></section>
    <section className="card-padded"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Questions supplémentaires</h2><button className="btn-outline" onClick={addField}><Plus className="h-4 w-4" /> Question</button></div><div className="space-y-3">{form.extra_fields.map((field) => <div key={field.id} className="grid gap-2 rounded-card-sm border p-3 md:grid-cols-[2fr_150px_120px_auto]"><input className="input" value={field.label} onChange={(e) => updateField(field.id, { label: e.target.value })} /><select className="input" value={field.type} onChange={(e) => updateField(field.id, { type: e.target.value as WebinarFormExtraField['type'] })}><option value="text">Texte</option><option value="textarea">Texte long</option><option value="select">Liste</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={field.required} onChange={(e) => updateField(field.id, { required: e.target.checked })} /> Obligatoire</label><button className="btn-danger" onClick={() => setForm({ ...form, extra_fields: form.extra_fields.filter((f) => f.id !== field.id) })}><Trash2 className="h-4 w-4" /></button>{field.type === 'select' && <input className="input md:col-span-4" placeholder="Options séparées par des virgules" value={(field.options ?? []).join(', ')} onChange={(e) => updateField(field.id, { options: e.target.value.split(',').map((v) => v.trim()).filter(Boolean) })} />}</div>)}</div></section>
    <section className="card-padded grid gap-4"><h2 className="font-bold">Sauvegarde Google Sheets</h2><label><span className="label">Lien de la feuille</span><input className="input" value={form.google_sheet_url ?? ''} onChange={(e) => setForm({ ...form, google_sheet_url: e.target.value || null })} /></label><label><span className="label">URL du webhook Google Apps Script</span><input className="input" type="password" value={form.backup_webhook_url ?? ''} onChange={(e) => setForm({ ...form, backup_webhook_url: e.target.value || null })} /></label><p className="text-xs text-slate-500">La plateforme reste la source principale. La feuille reçoit une copie après chaque inscription.</p></section>
    <button className="btn-primary" onClick={save}><Save className="h-4 w-4" /> Enregistrer et publier</button>
  </div>;
}
