// AUTO-GENERATED by generate-immigration-data.py — do not edit by hand.
// Lightweight structure of the Immigration course. Lesson bodies are fetched
// on demand from /content/immigration/<slug>.md (see fetchImmigrationLesson).
//
// 61 lessons · 3 sections · videos not recorded yet
// (vdocipherVideoId stays null until the lesson is filmed).

export interface ImmigrationLesson {
  id: string;
  slug: string;
  title: string;
  duration: string;
  vdocipherVideoId: string | null;
}
export interface ImmigrationModule {
  slug: string;
  title: string;
  lessons: ImmigrationLesson[];
}
export interface ImmigrationSection {
  slug: string;
  title: string;
  modules: ImmigrationModule[];
}
export interface ImmigrationBonus {
  slug: string;
  title: string;
  desc: string;
  file: string;
}

export const IMMIGRATION_COURSE = {
  slug: 'immigration-allemagne',
  title: "Immigration en Allemagne pour Algériens",
  totalLessons: 61,
} as const;

export const IMMIGRATION_SECTIONS: ImmigrationSection[] = [
  {
    "slug": "modules",
    "title": "Modules principaux",
    "modules": [
      {
        "slug": "module-0",
        "title": "Introduction — La vérité sur l'immigration en Allemagne",
        "lessons": [
          {
            "id": "0.1",
            "slug": "0-1-pourquoi-l-allemagne-te-veut-les",
            "title": "Pourquoi l'Allemagne te veut",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "0.2",
            "slug": "0-2-les-3-mensonges-qui-font-perdre-des-annees",
            "title": "Les 3 mensonges qui font perdre des années",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "0.3",
            "slug": "0-3-qui-reussit-vs-qui-echoue-le-vrai-facteur",
            "title": "Qui réussit vs qui échoue : le vrai facteur",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "0.4",
            "slug": "0-4-comment-utiliser-cette-formation-ta",
            "title": "Comment utiliser cette formation",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-1",
        "title": "MODULE 1 — CHOISIR TA VOIE D'ENTRÉE",
        "lessons": [
          {
            "id": "1.1",
            "slug": "1-1-comprendre-la-logique-toutes-les",
            "title": "Comprendre la logique : toutes",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.2",
            "slug": "1-2-les-voies-principales-travail-qualifie",
            "title": "Les voies principales",
            "duration": "9-11 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.3",
            "slug": "1-3-les-voies-familiales-regroupement",
            "title": "Les voies familiales",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.4",
            "slug": "1-4-les-voies-tremplin",
            "title": "Les voies « tremplin »",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.5",
            "slug": "1-5-les-voies-speciales-asile",
            "title": "Les voies spéciales",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.6",
            "slug": "1-6-le-test-quelle-voie-est-faite-pour-ta-situation",
            "title": "Le test : quelle voie est faite pour TA situation",
            "duration": "9-11 min",
            "vdocipherVideoId": null
          },
          {
            "id": "1.7",
            "slug": "1-7-l-erreur-de-choisir-la-mauvaise-porte",
            "title": "L'erreur de choisir la mauvaise porte",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-2",
        "title": "MODULE 2 — LES CONDITIONS RÉELLES",
        "lessons": [
          {
            "id": "2.1",
            "slug": "2-1-diplomes-ce-qui-compte-ce-qui-ne",
            "title": "Diplômes : ce qui compte, ce qui ne",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "2.2",
            "slug": "2-2-la-reconnaissance-des-diplomes",
            "title": "La reconnaissance des diplômes",
            "duration": "9-11 min",
            "vdocipherVideoId": null
          },
          {
            "id": "2.3",
            "slug": "2-3-niveau-d-allemand-exige-par-voie",
            "title": "Niveau d'allemand exigé par voie",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "2.4",
            "slug": "2-4-l-argent-a-prouver-combien-et-pourquoi",
            "title": "L'argent à prouver : combien et pourquoi",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-3",
        "title": "MODULE 3 — L'ALLEMAND : COMBIEN, COMMENT",
        "lessons": [
          {
            "id": "3.1",
            "slug": "3-1-a1-b2-de-quoi-tu-as-vraiment-besoin",
            "title": "A1 → B2 : de quoi tu as vraiment besoin",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "3.2",
            "slug": "3-2-plan-d-apprentissage-rapide-et-pas-cher",
            "title": "Plan d'apprentissage rapide (et pas cher)",
            "duration": "9-11 min",
            "vdocipherVideoId": null
          },
          {
            "id": "3.3",
            "slug": "3-3-goethe-telc-sd-quel-certificat-choisir",
            "title": "Goethe, telc, ÖSD : quel certificat choisir",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "3.4",
            "slug": "3-4-ou-passer-l-examen-depuis-l-algerie",
            "title": "Où passer l'examen depuis l'Algérie",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-4",
        "title": "MODULE 4 — LE DOSSIER QUI PASSE",
        "lessons": [
          {
            "id": "4.1",
            "slug": "4-1-la-checklist-complete-des-documents",
            "title": "La checklist complète des documents",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "4.2",
            "slug": "4-2-traduction-assermentee-ou-et-comment",
            "title": "Traduction assermentée : où et comment",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "4.3",
            "slug": "4-3-l-apostille-etape-par-etape-la",
            "title": "L'Apostille, étape par étape",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "4.4",
            "slug": "4-4-les-erreurs-de-dossier-qui-causent-un-refus",
            "title": "Les erreurs de dossier qui causent un refus",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-5",
        "title": "MODULE 5 — LE CV ET LA LETTRE ALLEMANDS",
        "lessons": [
          {
            "id": "5.1",
            "slug": "5-1-le-lebenslauf-comment-un",
            "title": "Le Lebenslauf : comment",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "5.2",
            "slug": "5-2-la-lettre-de-motivation-anschreiben",
            "title": "La lettre de motivation (Anschreiben)",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "5.3",
            "slug": "5-3-photo-format-details-qui-comptent",
            "title": "Photo, format, détails qui comptent",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "5.4",
            "slug": "5-4-modeles-prets-a-remplir",
            "title": "Modèles prêts à remplir",
            "duration": "5-7 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-6",
        "title": "MODULE 6 — TROUVER L'OFFRE",
        "lessons": [
          {
            "id": "6.1",
            "slug": "6-1-ou-chercher-sites-portails-agences-reelles",
            "title": "Où chercher (sites, portails, agences réelles)",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "6.2",
            "slug": "6-2-contacter-un-employeur-une-ecole-directement",
            "title": "Contacter un employeur / une école directement",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "6.3",
            "slug": "6-3-les-messages-qui-obtiennent-une-reponse",
            "title": "Les messages qui obtiennent une réponse",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "6.4",
            "slug": "6-4-reconnaitre-les-arnaques-et-faux-recruteurs",
            "title": "Reconnaître les arnaques et faux recruteurs",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-7",
        "title": "MODULE 7 — LE VISA ÉTAPE PAR ÉTAPE",
        "lessons": [
          {
            "id": "7.1",
            "slug": "7-1-quel-visa-pour-ta-situation",
            "title": "Quel visa pour ta situation",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "7.2",
            "slug": "7-2-blue-card-chancenkarte-fachkr-fte",
            "title": "Blue Card, Chancenkarte, Fachkräfte",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "7.3",
            "slug": "7-3-la-demande-en-ligne-et-le",
            "title": "La demande en ligne et",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "7.4",
            "slug": "7-4-remplir-les-formulaires-sans-erreur",
            "title": "Remplir les formulaires sans erreur",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-8",
        "title": "MODULE 8 — L'ENTRETIEN AU CONSULAT",
        "lessons": [
          {
            "id": "8.1",
            "slug": "8-1-ce-qu-on-te-demande-vraiment",
            "title": "Ce qu'on te demande vraiment",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "8.2",
            "slug": "8-2-preparer-tes-reponses-aux-questions-frequentes",
            "title": "Préparer tes réponses aux questions fréquentes",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "8.3",
            "slug": "8-3-prouver-que-tu-peux-te-financer",
            "title": "Prouver que tu peux te financer",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "8.4",
            "slug": "8-4-gerer-le-stress-et-eviter-les-erreurs",
            "title": "Gérer le stress et éviter les erreurs",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "8.4",
            "slug": "8-4-quoi-faire-en-cas-de-refus",
            "title": "Quoi faire en cas de refus",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-9",
        "title": "MODULE 9 — L'ARGENT ET LE COMPTE BLOQUÉ",
        "lessons": [
          {
            "id": "9.1",
            "slug": "9-1-le-compte-bloque-sperrkonto",
            "title": "Le compte bloqué (Sperrkonto)",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "9.2",
            "slug": "9-2-combien-exactement-les-montants-2026",
            "title": "Combien exactement (les montants 2026)",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "9.3",
            "slug": "9-3-comment-ouvrir-un-compte-bloque",
            "title": "Comment ouvrir un compte bloqué",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "9.4",
            "slug": "9-4-les-alternatives-au-compte-bloque",
            "title": "Les alternatives au compte bloqué",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          }
        ]
      },
      {
        "slug": "module-10",
        "title": "MODULE 10 — TES PREMIÈRES SEMAINES EN ALLEMAGNE",
        "lessons": [
          {
            "id": "10.1",
            "slug": "10-1-la-declaration-de-domicile",
            "title": "La déclaration de domicile",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "10.2",
            "slug": "10-2-le-titre-de-sejour-l-assurance-sante",
            "title": "Le titre de séjour, l'assurance santé",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "10.3",
            "slug": "10-3-compte-bancaire-carte-sim",
            "title": "Compte bancaire + carte SIM",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "10.4",
            "slug": "10-4-la-checklist-de-survie-des-30",
            "title": "La checklist de survie des 30",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      }
    ]
  },
  {
    "slug": "niches",
    "title": "Niches — 6 métiers",
    "modules": [
      {
        "slug": "niches",
        "title": "SECTION NICHES — LES 6 MÉTIERS LES PLUS DEMANDÉS",
        "lessons": [
          {
            "id": "N.0",
            "slug": "n-0-trouve-ton-metier-sur-la-liste",
            "title": "TROUVE TON MÉTIER SUR LA LISTE",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.1",
            "slug": "niche-1-sante-pflege-medical",
            "title": "SANTÉ (Pflege & médical)",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.2",
            "slug": "niche-2-it-informatique",
            "title": "IT & INFORMATIQUE",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.3",
            "slug": "niche-3-ingenierie",
            "title": "INGÉNIERIE",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.4",
            "slug": "niche-4-metiers-techniques-electricien",
            "title": "MÉTIERS TECHNIQUES",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.5",
            "slug": "niche-5-batiment-construction",
            "title": "BÂTIMENT & CONSTRUCTION",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "NICHE.6",
            "slug": "niche-6-transport-logistique",
            "title": "TRANSPORT & LOGISTIQUE",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          }
        ]
      }
    ]
  },
  {
    "slug": "tutos",
    "title": "Tutos pratiques",
    "modules": [
      {
        "slug": "tutos",
        "title": "SECTION TUTOS PRATIQUES — LES DÉMARCHES",
        "lessons": [
          {
            "id": "TUTO.1",
            "slug": "tuto-1-remplir-la-demande-de-visa-en-ligne",
            "title": "Remplir la demande de visa en ligne",
            "duration": "8-12 min",
            "vdocipherVideoId": null
          },
          {
            "id": "TUTO.2",
            "slug": "tuto-2-ouvrir-un-compte-bloque-sperrkonto",
            "title": "Ouvrir un compte bloqué (Sperrkonto)",
            "duration": "7-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "TUTO.3",
            "slug": "tuto-3-verifier-ton-diplome-sur-anabin",
            "title": "Vérifier ton diplôme sur anabin",
            "duration": "5-7 min",
            "vdocipherVideoId": null
          },
          {
            "id": "TUTO.4",
            "slug": "tuto-4-postuler-a-une-offre-de-l-annonce-a",
            "title": "Postuler à une offre",
            "duration": "8-10 min",
            "vdocipherVideoId": null
          },
          {
            "id": "TUTO.5",
            "slug": "tuto-5-faire-son-anmeldung-preparer-le",
            "title": "Faire son Anmeldung",
            "duration": "6-8 min",
            "vdocipherVideoId": null
          },
          {
            "id": "TUTO.6",
            "slug": "tuto-6-remplir-ton-lebenslauf-a-partir-du-modele",
            "title": "Remplir ton Lebenslauf à partir du modèle",
            "duration": "7-9 min",
            "vdocipherVideoId": null
          }
        ]
      }
    ]
  }
];

export const IMMIGRATION_BONUS: ImmigrationBonus[] = [
  {
    "slug": "b1-modeles",
    "title": "B1 — Tous les modèles",
    "desc": "CV, lettres, emails — prêts à remplir",
    "file": "B1-tous-les-modeles.pdf"
  },
  {
    "slug": "b2-liens",
    "title": "B2 — Liens, portails & contacts",
    "desc": "Tous les sites officiels + numéros utiles",
    "file": "B2-liens-portails-contacts.pdf"
  },
  {
    "slug": "b3-communaute",
    "title": "B3 — Communauté",
    "desc": "Accès au groupe privé + ressources",
    "file": "B3-communaute.pdf"
  },
  {
    "slug": "b4-maj",
    "title": "B4 — Mises à jour",
    "desc": "Les changements de lois et de seuils",
    "file": "B4-mises-a-jour.pdf"
  },
  {
    "slug": "cv-lebenslauf",
    "title": "Exemple — CV Lebenslauf",
    "desc": "Modèle de CV à l'allemande",
    "file": "exemple-CV-Lebenslauf.pdf"
  },
  {
    "slug": "anschreiben",
    "title": "Exemple — Lettre Anschreiben",
    "desc": "Lettre de motivation modèle",
    "file": "exemple-lettre-Anschreiben.pdf"
  },
  {
    "slug": "emails-allemand",
    "title": "Exemple — Emails en allemand",
    "desc": "Modèles d'emails aux employeurs",
    "file": "exemple-emails-allemand.pdf"
  }
];

// Flat list of all lessons in display order — handy for prev/next navigation.
export const IMMIGRATION_FLAT_LESSONS: Array<ImmigrationLesson & { moduleSlug: string; moduleTitle: string; sectionTitle: string }> =
  IMMIGRATION_SECTIONS.flatMap((s) =>
    s.modules.flatMap((m) =>
      m.lessons.map((l) => ({ ...l, moduleSlug: m.slug, moduleTitle: m.title, sectionTitle: s.title }))
    )
  );
